### ISSUE TITLE
Is tokenization.py needs to be uploaded to GCP?

### ISSUE THREAD

**Issue by lightercs** [cl-tohoku/bert-japanese#31]
Hi, I'm following your scripts to train a bert on my own datasets, I trained the tokenizer and created the pretraining data in local, and prepare to upload the tfrecord files to Google Cloud Storage (GCS) bucket for training.  Do I need to upload your [ tokenization.py ] to replace the one provided by git cloned google-bert when training the model ?  Thanks for your help.

**Comment by singletongue** [comment]
Hi, @lightercs.

[The training script we use](https://github.com/tensorflow/models/blob/v2.8.0/official/nlp/bert/run_pretraining.py) should work independently of tokenization, so you don't need to upload the tokenization script to the GCS bucket. Just give it a try!
(By the way, you may want to use tensorflow-models <= 2.8.0 since the training script seems to be deprecated in the lataset tensorflow-models.)

Thank you.

**Comment by lightercs** [comment]
Hi, @singletongue.
Thanks very much for your quick reply and the kindly advise!
