### ISSUE TITLE
Past pretrained model license change from CC-BY-SA 3.0 to Apache 2.0

### ISSUE THREAD

**Issue by icoxfog417** [cl-tohoku/bert-japanese#36]
Hi, I am supporting to develop large language model and defining license of model has becomo important recently. Therefore, 
 I would like to inquire how the licenese is defined for Tohoku BERT.

I have found the following issue that defines license of pretrained model as CC-BY-SA,  that comes from Wikipedia license.
https://github.com/cl-tohoku/bert-japanese/issues/7

However, current pretrained model license has been Apache 2.0. And the rationale for this change has not been disclosed in the commit.
https://github.com/cl-tohoku/bert-japanese/commit/89e406eefb72ae916d45a658a825ca4d9c3c09da

What situation did trigger this change?

**Comment by singletongue** [comment]
Hi, @icoxfog417.

As you mentioned, we formerly applied the CC-BY-SA license to the pretrained models.
However, we found that it is not recommended to apply a CC license to software.

https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software
https://creativecommons.jp/faq/#a6

Therefore, from the release of the models in 2023, we have decided to apply an OSS license instead of a CC license to the pretrained models as well as the codes.
We have chosen Apache 2.0, following the [original BERT by Google Research](https://github.com/google-research/bert).

Thank you.

**Comment by icoxfog417** [comment]
Hi @singletongue , thank you for your quick response and sharing the background! The CC license FAQ that describes `not recommended to apply a CC license to software` is rational. I will suggest to use software license to LLM developers. Thank you!
